Repository RAF-SI-2023/Banka-4-Frontend, pull requests merged in 2024-05, with the labels that each got.

#149 CD i Dockerfile
  .prow/build.yaml
  Dockerfile
Labels: size/L, lgtm, approved

#153 🦊
  cypress/e2e/firme/firme.cy.ts
  cypress/e2e/kartice/kartice.cy.ts
  cypress/e2e/korisnici/korisnici.cy.ts
  cypress/e2e/krediti/Dodajkrediti.cy.ts
  cypress/e2e/krediti/OdobriOdbiKredit.cy.ts
  cypress/e2e/menjacnica/menjacnica.cy.ts
  cypress/e2e/placanja/placanja.cy.ts
  cypress/e2e/placanja/util.ts
  cypress/e2e/proveraKursa/proveraKursa.cy.ts
  cypress/e2e/racuni/racuni.cy.ts
  cypress/e2e/util/util.ts
  cypress/e2e/verifikacija/verifikacija.cy.ts
  cypress/e2e/zaposleni/zaposleni.cy.ts
  src/korisnici/components/VerifikacijaPlacanja.tsx
  src/korisnici/pages/StranicaZaVerifikacijuPlacanja.tsx
  src/utils/apiRequest.tsx
Labels: lgtm, approved, size/XXL

#156 Prow test
  .prow/build.yaml
  src/App.tsx
  src/utils/permissions.ts
  src/utils/types.ts
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/createUserPage.tsx
  src/zaposleni/pages/editCompanyPage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
Labels: size/L, lgtm, approved

#148 karticeplacanjakreditiverifikacija
  src/moduls/Kartice/DetaljiKartice.tsx
  src/moduls/SviKrediti/Zaposlen.tsx
  src/zaposleni/components/Navbar.tsx
Labels: size/M, lgtm, approved

#159 Push to correct branch, prow, permission update
  .prow/build.yaml
  .prow/frontend.yaml
  cypress.config.ts
  cypress/downloads/downloads.htm
  cypress/e2e/placanja/placanja.cy.ts
  cypress/screenshots/my-image.png
  docker-compose.yml
  init-db.sql
  package-lock.json
  package.json
  src/moduls/Kartice/DetaljiKartice.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/SviKrediti/Zaposlen.tsx
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#164 Update apiUrl.ts
  src/utils/apiUrl.ts
Labels: lgtm, approved

#166 Harbor test PR
  README.md
  docker-compose.yml
Labels: lgtm, size/XS, approved

#167 Marzni racuni
  src/App.css
  src/berza/components/BuyOptionPopup.tsx
  src/berza/components/IzmiriMarginCallUplata.tsx
  src/utils/types.ts
Labels: size/L, lgtm, approved

#169 CI
  .prow/frontend.yaml
  src/utils/apiUrl.ts
Labels: lgtm, approved, size/S

#170 issue 144, permissions, navbar and company info page
  src/App.tsx
  src/utils/types.ts
  src/zaposleni/components/Navbar.tsx
  src/zaposleni/components/companyList.tsx
  src/zaposleni/pages/companyListPage.tsx
  src/zaposleni/pages/companyPage.tsx
  src/zaposleni/pages/employeeListPage.tsx
  src/zaposleni/pages/userListPage.tsx
Labels: size/L, lgtm, approved

#171 Vracam CI
  .prow/frontend.yaml
Labels: lgtm, size/XS, approved

#177 Oops
  .prow/frontend.yaml
Labels: lgtm, approved, size/S

#182 Env update
  .env.development
  .env.production
  .gitignore
  package-lock.json
  package.json
  src/utils/apiUrl.ts
Labels: size/L, lgtm, approved

#185 Fix za login koji nas je ganjao
  src/moduls/LogReg/LoginPage.tsx
Labels: lgtm, size/XS, approved

#186 Update init-db.sql
  init-db.sql
Labels: lgtm, approved

#189 Devizni currency fix
  src/zaposleni/pages/createAccountPage.tsx
Labels: size/M, lgtm, approved

#190 made hartijeOdVrenosti page and added route to navbar and app. #187
  src/App.tsx
  src/berza/pages/HartijeOdVrednosti.tsx
  src/utils/apiUrl.ts
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#191 LINT B💣💣MB
  .env.development
  package-lock.json
  package.json
  src/berza/components/AkcijeList.tsx
  src/berza/components/MojeAkcijeList.tsx
  src/berza/pages/AkcijePage.tsx
  src/berza/pages/DetaljiAkcijePage.tsx
  src/berza/pages/UserOptionsPage.tsx
  src/korisnici/components/CurrencyConverter.tsx
  src/korisnici/components/FormaZaPlacanje.tsx
  src/korisnici/components/FormaZaPrenos.tsx
  src/korisnici/components/PregledPlacanja.tsx
  src/korisnici/components/PrimaociPlacanja.tsx
  src/korisnici/components/VerifikacijaPlacanja.tsx
  src/korisnici/pages/StranicaZaPojedinacniRacunSaPocetneStraniceZaKorisnike.tsx
  src/korisnici/pages/StranicaZaVerifikacijuPlacanja.tsx
  src/korisnici/pages/UserHomePage.tsx
  src/menjacnica/ExchangeMainSection.tsx
  src/menjacnica/ExchangePage.tsx
  src/menjacnica/ExchangeRatesTable.tsx
  src/menjacnica/TransferDetails.tsx
  src/moduls/Kartice/DetaljiKartice.tsx
  src/moduls/Kartice/DodajKarticu.tsx
  src/moduls/Kartice/ListaTransakcija.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/LogReg/RegistrationPage.tsx
  src/moduls/PojedinacniKredit/KreditiTabela.tsx
  src/moduls/PojedinacniKredit/PojedinacniKreditStranica.tsx
  src/moduls/SviKrediti/TabelaKrediti.tsx
  src/moduls/SviKrediti/TabelaKrediti2.tsx
  src/moduls/SviKrediti/Zaposlen.tsx
  src/moduls/SviKrediti/listaKredita.tsx
  src/moduls/TerminskiUgovori/pages/ContractsPage.tsx
  src/moduls/TerminskiUgovori/pages/SpecificContractListPage.tsx
  src/moduls/TrazenjeKredita/TraziKreditOdBanke.tsx
  src/utils/alerts.tsx
  src/utils/apiRequest.tsx
  src/zaposleni/components/Navbar.tsx
  src/zaposleni/components/companyList.tsx
  src/zaposleni/components/userList.tsx
  src/zaposleni/pages/TransactionPage.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/companyListPage.tsx
  src/zaposleni/pages/companyPage.tsx
  src/zaposleni/pages/createAccountPage.tsx
  src/zaposleni/pages/createUserPage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
  src/zaposleni/pages/editUserPage.tsx
  src/zaposleni/pages/employeeListPage.tsx
  src/zaposleni/pages/userListPage.tsx
  src/zaposleni/pages/userPage.tsx
Labels: lgtm, approved, size/XL
