Repository RAF-SI-2023/Banka-4-Frontend, pull requests merged in 2024-06, with the labels that each got.

#192 Update build.yaml
  .prow/build.yaml
Labels: size/XS

#195 Navbar fix
  package-lock.json
  src/zaposleni/components/Navbar.tsx
Labels: size/M, lgtm, approved

#205 Vracanje stvari koje su bile sklonjene
  .env.development
  src/korisnici/pages/UserHomePage.tsx
  src/zaposleni/components/Navbar.tsx
Labels: size/M, lgtm, approved

#207 Pocetna i rute
  .env.development
  .env.local
  src/korisnici/pages/UserHomePage.tsx
  src/menjacnica/ExchangeMainSection.tsx
  src/menjacnica/ExchangeRatesTable.tsx
  src/menjacnica/TransferDetails.tsx
  src/utils/types.ts
Labels: size/M, lgtm, approved

#209 Bleh
  src/korisnici/pages/UserHomePage.tsx
Labels: lgtm, size/XS, approved

#214 Dev final
  src/menjacnica/ExchangeMainSection.tsx
  src/menjacnica/ExchangePage.tsx
  src/menjacnica/ExchangeRatesTable.tsx
  src/menjacnica/TransferDetails.tsx
Labels: size/L, lgtm, approved

#216 Update Dockerfile
  Dockerfile
Labels: lgtm, size/XS, approved

#218 Dockerfile update
  Dockerfile
Labels: lgtm, size/XS, approved

#219 Update build.yaml & Dockerfile
  .prow/build.yaml
  Dockerfile
Labels: size/M, lgtm, approved

#221 ispravljen helm
  .prow/build.yaml
  Dockerfile
Labels: size/M, lgtm, approved

#222 orders
  src/App.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/pages/ListaPorudzbinaKorisnici.tsx
  src/berza/pages/NewOrder.tsx
  src/berza/types/types.ts
  src/utils/permissions.ts
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#223 Update Dockerfile
  Dockerfile
Labels: lgtm, size/XS, approved

#224 Dev final, added employee edit permission grouping, OTC page visible to everyone
  src/App.tsx
  src/berza/components/ForeignOtcList.tsx
  src/berza/components/MakeOfferPopup.tsx
  src/berza/components/OurOtcList.tsx
  src/berza/components/RecievedOtcOffers.tsx
  src/berza/components/SellStockPopup.tsx
  src/berza/pages/OtcPage.tsx
  src/berza/types/types.ts
  src/zaposleni/components/Navbar.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
Labels: lgtm, approved, size/XL

#226 Bagovi, ATM, kreiranje marznog racuna
  src/App.tsx
  src/berza/components/AkcijeList.tsx
  src/berza/components/BuyStockPopup.tsx
  src/korisnici/components/VerifikacijaPlacanja.tsx
  src/korisnici/data/Racuni.tsx
  src/korisnici/pages/ATMPage.tsx
  src/korisnici/pages/PlacanjePage.tsx
  src/moduls/Kartice/DetaljiKartice.tsx
  src/moduls/Kartice/DodajKarticu.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/utils/apiUrl.ts
  src/utils/types.ts
  src/zaposleni/components/Navbar.tsx
  src/zaposleni/pages/createAccountPage.tsx
Labels: size/L, lgtm, approved

#228 Prow
  .prow/build.yaml
  Dockerfile
  package.json
Labels: lgtm, size/XS, approved

#230 Update build.yaml
  .prow/build.yaml
Labels: lgtm, size/XS, approved

#231 🚀🚀🚀🚀
  .env.local
  package-lock.json
  package.json
  src/WSTest.tsx
  src/menjacnica/TransferDetails.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/utils/logRegStyles.ts
Labels: lgtm, approved, size/XXL

#233 Dev final2
  src/berza/components/MojeAkcijeList.tsx
  src/berza/pages/HartijeOdVrednosti.tsx
  src/korisnici/pages/UserHomePage.tsx
  src/profit/ProfitPage.tsx
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#235 Fix
  src/berza/components/MojeAkcijeList.tsx
  src/berza/pages/HartijeOdVrednosti.tsx
  src/korisnici/pages/UserHomePage.tsx
  src/profit/ProfitPage.tsx
  src/utils/apiUrl.ts
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#236 Build bi trebalo
  .env.local
  src/WSTest.tsx
Labels: size/M, lgtm, approved

#238 dizajn i bag
  src/berza/components/BuyOptionPopupContract.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/pages/ListaPorudzbinaKorisnici.tsx
  src/moduls/SviKrediti/TabelaKrediti.tsx
  src/moduls/SviKrediti/Zaposlen.tsx
  src/moduls/SviKrediti/listaKredita.tsx
  src/moduls/TerminskiUgovori/pages/ContractsPage.tsx
Labels: lgtm, approved, size/XL

#239 Final
  .env.local
  src/berza/components/CallsList.tsx
  src/berza/components/PutsList.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/pages/ListaPorudzbinaKorisnici.tsx
  src/korisnici/components/PregledPlacanja.tsx
  src/korisnici/pages/StranicaZaPojedinacniRacunSaPocetneStraniceZaKorisnike.tsx
  src/korisnici/pages/UserHomePage.tsx
  src/moduls/Kartice/ListaTransakcija.tsx
  src/moduls/SviKrediti/listaKredita.tsx
  src/profit/ProfitPage.tsx
  src/profit/ProfitTable.tsx
  src/utils/types.ts
  src/zaposleni/pages/TransactionPage.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
Labels: size/L, lgtm, approved

#240 Finalni
  src/berza/components/BuyStockPopup.tsx
  src/berza/components/CallsList.tsx
  src/berza/components/MojeAkcijeList.tsx
  src/berza/components/PutsList.tsx
  src/berza/pages/AkcijePage.tsx
  src/berza/pages/OpcijePage.tsx
  src/berza/types/types.ts
  src/moduls/TerminskiUgovori/pages/SpecificContractListPage.tsx
  src/utils/types.ts
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#241 OTC i boja
  src/berza/components/BuyStockPopup.tsx
  src/berza/components/CallsList.tsx
  src/berza/components/MakeOfferPopup.tsx
  src/berza/components/MojeAkcijeList.tsx
  src/berza/components/PutsList.tsx
  src/berza/components/SellStockPopup.tsx
  src/berza/pages/AkcijePage.tsx
  src/berza/pages/OpcijePage.tsx
  src/berza/types/types.ts
  src/moduls/TerminskiUgovori/pages/SpecificContractListPage.tsx
  src/utils/types.ts
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#242 Futures
  src/berza/components/MakeOfferPopup.tsx
  src/berza/components/SellStockPopup.tsx
  src/berza/pages/HartijeOdVrednosti.tsx
  src/moduls/TerminskiUgovori/pages/SpecificContractListPage.tsx
Labels: lgtm, approved, size/S

#244 Fin u main
  src/berza/components/MakeOfferPopup.tsx
  src/berza/components/SellStockPopup.tsx
  src/zaposleni/components/Navbar.tsx
Labels: lgtm, approved, size/S

#260 Login, Register i ResetPassword Gotove + Responsive NavBar
  public/backgground.jpg
  src/App.tsx
  src/korisnici/pages/ResetPasswordPage.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/LogReg/RegistrationPage.tsx
  src/zaposleni/components/NavbarJovan.tsx
Labels: lgtm, approved, size/XL

#264 ≽^•⩊•^≼
  src/utils/apiUrl.ts
  src/utils/types.ts
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/companyPage.tsx
  src/zaposleni/pages/createAccountPage.tsx
Labels: size/L, lgtm, approved

#265 Registrations steps 2 and 3 styling
  public/backgground.jpg
  public/diktator100.png
  src/App.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/pages/ListaPorudzbinaKorisnici.tsx
  src/berza/pages/NewOrder.tsx
  src/berza/types/types.ts
  src/korisnici/pages/ResetPasswordPage.tsx
  src/korisnici/pages/StranicaZaVerifikacijuPlacanja.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/LogReg/RegistrationPage.tsx
  src/moduls/SviKrediti/NeZaposlen.tsx
  src/moduls/SviKrediti/TabelaKrediti.tsx
  src/moduls/SviKrediti/TabelaKrediti2.tsx
  src/moduls/SviKrediti/listaKredita.tsx
  src/profit/ProfitPage.tsx
  src/utils/apiUrl.ts
  src/utils/types.ts
  src/zaposleni/components/NavbarJovan.tsx
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/companyListPage.tsx
  src/zaposleni/pages/companyPage.tsx
  src/zaposleni/pages/createAccountPage.tsx
  src/zaposleni/pages/createCompanyPage.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/createUserPage.tsx
  src/zaposleni/pages/employeeListPage.tsx
  src/zaposleni/pages/userListPage.tsx
Labels: lgtm, approved, size/XXL

#266 Na pogresnu granu sam mergovao lmao oops
  package-lock.json
  public/diktator100.png
  src/moduls/LogReg/RegistrationPage.tsx
Labels: size/M, lgtm, approved

#267 Jun rebase
  package-lock.json
Labels: size/M, lgtm, approved

#268 Revert "Registrations steps 2 and 3 styling"
  public/backgground.jpg
  public/diktator100.png
  src/App.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/pages/ListaPorudzbinaKorisnici.tsx
  src/berza/pages/NewOrder.tsx
  src/berza/types/types.ts
  src/korisnici/pages/ResetPasswordPage.tsx
  src/korisnici/pages/StranicaZaVerifikacijuPlacanja.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/LogReg/RegistrationPage.tsx
  src/moduls/SviKrediti/NeZaposlen.tsx
  src/moduls/SviKrediti/TabelaKrediti.tsx
  src/moduls/SviKrediti/TabelaKrediti2.tsx
  src/moduls/SviKrediti/listaKredita.tsx
  src/profit/ProfitPage.tsx
  src/utils/apiUrl.ts
  src/utils/types.ts
  src/zaposleni/components/NavbarJovan.tsx
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/companyListPage.tsx
  src/zaposleni/pages/companyPage.tsx
  src/zaposleni/pages/createAccountPage.tsx
  src/zaposleni/pages/createCompanyPage.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/createUserPage.tsx
  src/zaposleni/pages/employeeListPage.tsx
  src/zaposleni/pages/userListPage.tsx
Labels: lgtm, approved, size/XXL

#269 Revert "Jun rebase"
  package-lock.json
Labels: size/M, lgtm, approved

#271 ATM: Dodatak
  src/korisnici/pages/ATMPage.tsx
Labels: size/M, lgtm, approved

#276 Dizajn
  src/korisnici/components/FormaZaPlacanje.tsx
  src/korisnici/pages/ATMPage.tsx
  src/korisnici/pages/PlacanjePage.tsx
  src/korisnici/pages/ResetPasswordPage.tsx
  src/menjacnica/ExchangePage.tsx
Labels: size/M, lgtm, approved

#279 Obrisana Firma iz types
  src/berza/components/BuyStockPopup.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/types/types.ts
Labels: size/L, lgtm, approved

#280 OTC mock data + removed Navbar
  src/App.tsx
  src/berza/components/otcComponents/MojePonude.tsx
  src/berza/components/otcComponents/Ponude.tsx
  src/berza/components/otcComponents/PrihvatanjePonuda.tsx
  src/berza/pages/OtcPage.tsx
  src/berza/pages/OtcPageKorisnik.tsx
  src/zaposleni/components/Navbar.tsx
  src/zaposleni/components/NavbarJovan.tsx
Labels: lgtm, approved, size/XL

#282 Shat
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/LogReg/RegistrationPage.tsx
  src/utils/types.ts
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
  src/zaposleni/pages/employeeListPage.tsx
Labels: size/M, lgtm, approved

#284 Fixovi za cypress
  .prow/frontend.yaml
  cypress/e2e/kartice/kartice.cy.ts
  cypress/e2e/krediti/Dodajkrediti.cy.ts
  cypress/e2e/krediti/OdobriOdbiKredit.cy.ts
  cypress/e2e/menjacnica/menjacnica.cy.ts
  cypress/e2e/placanja/placanja.cy.ts
  cypress/e2e/racuni/racuni.cy.ts
  cypress/e2e/testpages.cy.ts
  cypress/e2e/util/util.ts
  cypress/e2e/zaposleni/zaposleni.cy.ts
  src/menjacnica/ExchangeMainSection.tsx
  src/utils/types.ts
Labels: size/M, lgtm, approved

#286 OTC izmene + Marzni racuni + Futuri
  package-lock.json
  package.json
  src/berza/components/BuyOptionPopupContract.tsx
  src/berza/components/MakeOfferPopup.tsx
  src/berza/components/RecievedOtcOffers.tsx
  src/berza/components/SendOtcOffers.tsx
  src/berza/components/otcComponents/MojePonude.tsx
  src/berza/components/otcComponents/Ponude.tsx
  src/berza/components/otcComponents/PrihvatanjePonuda.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/berza/pages/ListaPorudzbinaKorisnici.tsx
  src/berza/pages/OtcPage.tsx
  src/berza/types/types.ts
  src/korisnici/pages/UserHomePage.tsx
  src/moduls/TerminskiUgovori/pages/ContractsPage.tsx
  src/profit/ProfitPage.tsx
  src/zaposleni/pages/companyPage.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/createUserPage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
  src/zaposleni/pages/editUserPage.tsx
  src/zaposleni/pages/userPage.tsx
Labels: lgtm, approved, size/XXL

#289 Hartije od vrednosti - Sofijin kod
  cypress/e2e/placanja/placanja.cy.ts
  package-lock.json
  package.json
  src/App.tsx
  src/berza/pages/hartije/HartijeOdVrednosti.tsx
  src/berza/pages/hartije/HartijePopup.tsx
  src/berza/pages/hartije/OptionsTable.tsx
  src/berza/pages/hartije/OrdersTable.tsx
  src/berza/types/types.ts
  src/profit/ProfitHartijeTable.tsx
Labels: lgtm, approved, size/XL

#291 OTC unutar banke
  src/berza/components/otcComponents/MojePonude.tsx
  src/berza/components/otcComponents/Ponude.tsx
  src/berza/components/otcComponents/PrihvatanjePonuda.tsx
  src/berza/pages/OtcPageKorisnik.tsx
Labels: size/M, lgtm, approved

#292 Rerouting na pocetnu uvek
  cypress/e2e/kartice/kartice.cy.ts
  cypress/e2e/korisnici/korisnici.cy.ts
  cypress/e2e/racuni/racuni.cy.ts
  cypress/e2e/util/util.ts
  src/moduls/LogReg/LoginPage.tsx
Labels: size/M, lgtm, approved, papa-bless

#293 Kostur prosirenja cypress i testovi za marzne i akcije
  cypress/e2e/berza/akcije.cy.ts
  cypress/e2e/berza/otcunutar.cy.ts
  cypress/e2e/berza/porudzbine.cy.ts
  cypress/e2e/berza/terminski.cy.ts
  cypress/e2e/placanja/placanja.cy.ts
  cypress/e2e/racuni/racuni.cy.ts
  src/berza/components/AkcijeList.tsx
  src/berza/components/BuyOptionPopupContract.tsx
  src/berza/components/BuyStockPopup.tsx
  src/berza/components/otcComponents/MojePonude.tsx
  src/berza/components/otcComponents/Ponude.tsx
  src/berza/components/otcComponents/PrihvatanjePonuda.tsx
  src/berza/pages/AkcijePage.tsx
  src/berza/pages/ListaPorudzbina.tsx
  src/profit/ProfitHartijeTable.tsx
Labels: size/L, lgtm, approved

#294 Porudžbine ispravka
  src/berza/pages/NewOrder.tsx
Labels: lgtm, approved, size/S

#295 Berza fixovi
  cypress/e2e/berza/terminski.cy.ts
  cypress/e2e/util/util.ts
  src/berza/components/BuyStockPopup.tsx
  src/berza/components/CallsList.tsx
  src/berza/components/PutsList.tsx
  src/berza/pages/OpcijePage.tsx
  src/berza/pages/hartije/OptionsTable.tsx
  src/berza/pages/hartije/OrdersTable.tsx
  src/berza/types/types.ts
  src/profit/ProfitHartijeTable.tsx
Labels: size/M, lgtm, approved
