Repository RAF-SI-2023/Banka-4-Frontend, pull requests merged in 2024-04, with the labels that each got.

#100 Exchange table fix
  src/korisnici/components/CurrencyConverter.tsx
  src/menjacnica/ExchangeRatesTable.tsx
  src/zaposleni/components/Navbar.tsx
Labels: size/L, lgtm, approved

#107 Lazy loading i tsnocheck fixovano
  package-lock.json
  package.json
  src/App.tsx
  src/korisnici/components/CurrencyConverter.tsx
Labels: size/L, lgtm, approved

#108 Omiljeni korisnici i ts-ignore removano
  src/korisnici/components/DropdownMenu.tsx
  src/korisnici/components/FormaZaPlacanje.tsx
  src/korisnici/components/FormaZaPrenos.tsx
  src/korisnici/components/PregledPlacanja.tsx
  src/korisnici/components/PrimaociPlacanja.tsx
  src/korisnici/pages/PlacanjePage.tsx
  src/moduls/Kartice/DetaljiKartice.tsx
  src/moduls/Kartice/DodajKarticu.tsx
  src/moduls/Kartice/ListaTransakcija.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/moduls/LogReg/LoginPage.tsx
  src/moduls/LogReg/RegistrationPage.tsx
Labels: lgtm, approved, size/XL

#113 Test commit za automatsko approvanje
  src/App.tsx
Labels: size/M

#117 fixed jwt removal on app exit, explored the edges of the known universe
  src/App.tsx
  src/korisnici/components/CurrencyConverter.tsx
Labels: size/L, lgtm, approved

#119 logout, navbar, pages, tables, 404 and more
  public/404gif1.gif
  public/404gif2.gif
  src/App.tsx
  src/berza/components/AkcijeList.tsx
  src/berza/components/CallsList.tsx
  src/berza/components/MojeAkcijeList.tsx
  src/berza/components/PutsList.tsx
  src/berza/components/UserOptionList.tsx
  src/korisnici/components/PregledPlacanja.tsx
  src/korisnici/components/PrimaociPlacanja.tsx
  src/korisnici/pages/UserHomePage.tsx
  src/menjacnica/ExchangeRatesTable.tsx
  src/moduls/DodatneStranice/NotFoundPage.tsx
  src/moduls/Kartice/ListaTransakcija.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/moduls/PojedinacniKredit/TransakcijeTabela.tsx
  src/moduls/SviKrediti/TabelaKrediti.tsx
  src/moduls/SviKrediti/TabelaKrediti2.tsx
  src/utils/ScrollableTableBody.tsx
  src/utils/alerts.tsx
  src/utils/apiRequest.ts
  src/utils/tableStyles.ts
  src/zaposleni/components/Navbar.tsx
  src/zaposleni/components/companyList.tsx
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/components/userList.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/companyListPage.tsx
  src/zaposleni/pages/createAccountPage.tsx
  src/zaposleni/pages/createCompanyPage.tsx
  src/zaposleni/pages/createEmployeePage.tsx
  src/zaposleni/pages/createUserPage.tsx
  src/zaposleni/pages/editCompanyPage.tsx
  src/zaposleni/pages/editEmployeePage.tsx
  src/zaposleni/pages/editUserPage.tsx
  src/zaposleni/pages/employeeListPage.tsx
  src/zaposleni/pages/listsPage.tsx
  src/zaposleni/pages/userListPage.tsx
  src/zaposleni/pages/userPage.tsx
Labels: lgtm, approved, size/XXL

#120 Terminski ugovori
  public/bingEnergy.jpeg
  public/bingMetals.jpeg
  public/geminiAgr.jpeg
  public/geminiMeats.jpeg
  public/geminiSofts.jpeg
  src/App.tsx
  src/berza/components/BuyStockPopup.tsx
  src/moduls/TerminskiUgovori/components/termKartice.tsx
  src/moduls/TerminskiUgovori/pages/ContractsPage.tsx
  src/moduls/TerminskiUgovori/pages/SpecificContractListPage.tsx
  src/moduls/TerminskiUgovori/pages/TerminskiUgovoriPage.tsx
Labels: size/L, lgtm, approved

#122 Fix scroll fixes
  src/berza/components/AkcijeList.tsx
  src/berza/components/CallsList.tsx
  src/berza/components/MojeAkcijeList.tsx
  src/berza/components/PutsList.tsx
  src/berza/components/UserOptionList.tsx
  src/korisnici/components/PregledPlacanja.tsx
  src/korisnici/components/PrimaociPlacanja.tsx
  src/korisnici/pages/UserHomePage.tsx
  src/menjacnica/ExchangeRatesTable.tsx
  src/moduls/Kartice/ListaTransakcija.tsx
  src/moduls/Kartice/PregledKartica.tsx
  src/moduls/PojedinacniKredit/TransakcijeTabela.tsx
  src/moduls/SviKrediti/TabelaKrediti.tsx
  src/moduls/SviKrediti/TabelaKrediti2.tsx
  src/moduls/TerminskiUgovori/pages/ContractsPage.tsx
  src/moduls/TerminskiUgovori/pages/SpecificContractListPage.tsx
  src/utils/ScrollableTableBody.tsx
  src/utils/tableStyles.ts
  src/zaposleni/components/companyList.tsx
  src/zaposleni/components/employeeList.tsx
  src/zaposleni/components/userList.tsx
  src/zaposleni/pages/accountPage.tsx
  src/zaposleni/pages/userPage.tsx
Labels: size/L, lgtm, approved

#127 Fixovi za sitne stvari
  src/App.tsx
  src/korisnici/components/FormaZaPlacanje.tsx
  src/moduls/SviKrediti/listaKredita.tsx
  src/zaposleni/components/Navbar.tsx
Labels: lgtm, approved, size/S

#136 Permission check metoda
  src/utils/permissions.ts
Labels: lgtm, size/XS, approved

#138 Jos editovanja permisija jer sam kreten
  src/utils/permissions.ts
Labels: size/M, lgtm, approved

#139 Permisije, kraj, valjda
  src/utils/permissions.ts
Labels: size/M, lgtm, approved
